USE Music_DB;

GO


CREATE PROCEDURE sp_truncateTABLES_IN AS
BEGIN
TRUNCATE TABLE staging.MUSICALHISTORY_in;
TRUNCATE TABLE staging.SUBMUSICALGENRE_in;
TRUNCATE TABLE staging.ALBUM_in;
END

GO

CREATE PROCEDURE sp_truncateTABLES_OUT AS
BEGIN
TRUNCATE TABLE staging.MUSICALHISTORY_out;
TRUNCATE TABLE staging.SUBMUSICALGENRE_out;
TRUNCATE TABLE staging.ALBUM_out;
END

GO

CREATE PROCEDURE sp_truncateTABLES_SOURCE AS
BEGIN
TRUNCATE TABLE dbo.MUSICALHISTORY;
TRUNCATE TABLE dbo.SUBMUSICALGENRE;
TRUNCATE TABLE dbo.ALBUM;
END